### ISSUE TITLE
Decide on our Vagrant build

### ISSUE THREAD

**Issue by bess** [curationexperts/Berlin2018#10]
- [ ] Do we need anything specific for Fedora?
- [ ] Can we get it well ahead of time so David and Andrew can test the fedora side?
- [ ] Can we add Samvera stack contents to this? https://github.com/fcrepo4-exts/fcrepo4-vagrant/releases/tag/fcrepo4-vagrant-4.7.5

**Comment by bess** [comment]
Ideally, we'd love to use the same vagrant build for the samvera side of things and the fedora exercises. The fedora exercises need camel and some configuration that's on the fcrepo4 vagrant build referenced above.

**Comment by mark-dce** [comment]
The two gating items are:
1. Determining the release version of Hyrax we want to use
1. Building out the sample application with that version of Hyrax and pushing it to repocamp/berrlin2018

The key issue will be determining what release of Hyrax we want to use.  I'm hopeful that any major releases will be out well before November.  I can build a prototype box in August using [repocamp/ohsu2018](https://github.com/RepoCamp/ohsu2018) to get most of the scripts complete and then we can talk to Steve Van Tuyl and Tom Johnson about anticipated Hyrax release schedules.

**Comment by dwilcox** [comment]
@mark-dce just checking in to see if you've made any progress on this? I'd like to get a VM setup soon so we can start testing. Ideally the Samvera application(s) would be built on top of the latest Fedora release VM (4.7.5): 
https://github.com/fcrepo4-exts/fcrepo4-vagrant/releases/tag/fcrepo4-vagrant-4.7.5

**Comment by mark-dce** [comment]
@dwilcox I'm sitting across the room working on a build...

Can I use https://app.vagrantup.com/fcrepo/boxes/fcrepo4-base as a finished version of https://github.com/fcrepo4-exts/fcrepo4-vagrant? or should I plan on building the `fcrepo4-vagrant` box from the GitHub repo?

A related question - the fcrepo4 box appears to be based on 14.04 LTS (end of life April 2019), the current Samvera camp build assumes a 16.04 LTS (end of life April 2021) base (and may have some dependencies on 16.04 not met by 14.04).  And I'm actually wondering if we might want to plan on updating both to 18.04 LTS (end of life April 2023)?

**Comment by dwilcox** [comment]
I passed a fully-built Fedora 4.7.5 VM on a USB drive to @mark-dce . We could probably upgrade to a more recent LTS as well - I'll check with Andrew to see if he thinks there would be any issues.

**Comment by dwilcox** [comment]
We now have a working Vagrant build: https://github.com/curationexperts/camper
