### ISSUE TITLE
Revise Fedora and Samvera Overview slide deck from Oxford 2017

### ISSUE THREAD

**Issue by bess** [curationexperts/Berlin2018#12]

**Comment by dwilcox** [comment]
Slides from last year: https://docs.google.com/presentation/d/1HOLydKYglrp_6KLXzLhkmPpYtnDL2ejj4h1LXlOzLQA/edit?usp=sharing

**Comment by dwilcox** [comment]
@bess I updated the Fedora part of these slides. Can you take a look at the Samvera content?
