### ISSUE TITLE
Agree on syllabus

### ISSUE THREAD

**Issue by bess** [curationexperts/Berlin2018#15]

**Comment by bess** [comment]
Draft syllabus: https://docs.google.com/document/d/1GOeYD7oy9Di6MUOci_Z3Tz4Na5vkfpeBNSE_xo9Me_0/edit#

**Comment by mark-dce** [comment]
Added comments on these areas:
- [ ] What does a mix of Fedora and Samvera tickets looks like?  Do we need to take this into account when pairing folks?
- [ ] When is the VM distributed and tested (i.e. you've copied it correctly and can ssh in)?
- [ ] Is Rails for Zombies the best use of time in a compressed class, or should we make this a pre-work assignment
- [ ] On day 4, encourage teams do sketch out their demo before lunch - make sure they have a good plan before taking a break.
