### ISSUE TITLE
Create list of preparation instructions for attendees

### ISSUE THREAD

**Issue by dwilcox** [curationexperts/Berlin2018#23]
- [ ] Have or create a GitHub account
- [ ] Run through Rails for Zombies
- [ ] Install the VM
- [] https://wiki.duraspace.org/display/FEDORA5x/How+to+Inspect+Event+Messages+Generated+by+Fedora

**Comment by mark-dce** [comment]
We just learned in the camp at Duke two weeks ago that Rails for Zombies now requires a credit card for access, so we've swapped RailsBridge Intro to Rails in it's place.  

Please see #25, especially related to https://github.com/RepoCamp/berlin2018/wiki/Preparation-and-Logistics#pre-class-homework and see if that looks like the right preparation - we generally send this info out in an e-mail the week before class.

I'm checking a few final bits and should have the VM pushed to AWS shortly.
