### ISSUE TITLE
Make RepoCamp Berlin2018 Repository

### ISSUE THREAD

**Issue by bess** [curationexperts/Berlin2018#3]
- [x] Copy curriculum from OHSU 2018 camp

**Comment by mark-dce** [comment]
See
https://github.com/RepoCamp/berlin2018 and  
https://github.com/RepoCamp/berlin2018/wiki

Also https://docs.google.com/document/d/14Hkw0QwHQXyk5N5a9veo71Z10S2uhTHP327Kt4NFL7Q/edit?usp=sharing
