### ISSUE TITLE
Update Camp Location 

### ISSUE THREAD

**Issue by jmfrenzel** [curationexperts/Berlin2018#31]
### Descriptive summary of request
[Preparation-and-Logistics#location](https://github.com/RepoCamp/berlin2018/wiki/Preparation-and-Logistics#location)
### Existing 
Wiki has Duke Camp data 
###  Expected 
Wiki displays Berlin data, see 
https://wiki.duraspace.org/display/FF/2018-11+Fedora+and+Samvera+Camp+Berlin

**Comment by dwilcox** [comment]
The page has been updated.
